#!/usr/bin/env python3

import requests
import argparse
from concurrent.futures import ThreadPoolExecutor

class Color:
    RESET = "\033[0m"
    BOLD = "\033[1m"
    BRIGHT_GREEN = "\033[92m"
    BRIGHT_MAGENTA = "\033[95m"
    WHITE = "\033[37m"

print(Color.BRIGHT_MAGENTA + Color.BOLD + r"""
___________.__            .___                    
\_   _____/|__| ____    __| _/      _____   ____  
 |    __)  |  |/    \  / __ |      /     \_/ __ \ 
 |     \   |  |   |  \/ /_/ |     |  Y Y  \  ___/ 
 \___  /   |__|___|  /\____ |_____|__|_|  /\___  >
     \/            \/      \/_____/     \/     \/
     
     
v1.0
""" + Color.RESET)

print(Color.WHITE + """
 ************************************************
* Welcome To Find_Me                             *
* Find hidden endpoints in a web server          *
 ************************************************
""" + Color.RESET)

# -------- ARGUMENTS --------
parser = argparse.ArgumentParser(description="Find hidden web endpoints")
parser.add_argument("-u", "--url", required=True, help="Target URL")
parser.add_argument("-w", "--wordlist", required=True, help="Wordlist file")
parser.add_argument("-t", "--threads", type=int, default=50, help="Threads (default 50)")
args = parser.parse_args()

url = args.url.rstrip("/")
wordlist = args.wordlist

# -------- FUNCTION --------
def send_req(endpoint):
    endpoint = endpoint.strip()
    if not endpoint:
        return
    try:
        r = requests.get(f"{url}/{endpoint}", timeout=3)
        if r.status_code == 200:
            print(Color.BRIGHT_GREEN + f"/{endpoint} : 200" + Color.RESET)
    except:
        pass

# -------- RUN --------
with open(wordlist, "r", encoding="latin-1", errors="ignore") as f:
    lines = f.readlines()
with ThreadPoolExecutor(max_workers=args.threads) as executor:
    executor.map(send_req, lines)
